### ISSUE TITLE
Where did the `rest-api-sdk-ruby` and `merchant-sdk-ruby` repositories go?

### ISSUE THREAD

**Issue by magni-** [paypal/.github#1]
These are the repositories for two public Ruby gems, [`paypal-sdk-rest`](https://rubygems.org/gems/paypal-sdk-rest) and [`paypal-sdk-merchant`](https://rubygems.org/gems/paypal-sdk-merchant).

Both of these gems had new releases published on October 17, but as the repositories are gone, we can't see what the changes are without downloading the gems locally.

**Comment by magni-** [comment]
All of the Ruby links [here](https://developer.paypal.com/api/nvp-soap/nvpsoap-sdks/) now 404. Why not make these repositories public archives instead of removing them?

**Comment by devchristina** [comment]
Hi @magni- These repos did not actually have anything released in a very long time. If there were any updates to the repos, it was in preparation of moving them to private. These repos were in public archive for a long period of time. They do not provide developers with the newest way to integrate and oftentimes are using outdated endpoints or products. We're currently working on a new set of server side SDKs that'll showcase our new integration pattern and is supported by the product and engineering teams at PayPal.

**Comment by devchristina** [comment]
If you need access to these repos, please let me know.

**Comment by magni-** [comment]
I realized I'm actually able to easily see the diffs on RubyGems without needing to download the gems locally via the `Review changes` link:
- https://my.diffend.io/gems/paypal-sdk-rest/1.7.4/1.7.5
- https://my.diffend.io/gems/paypal-sdk-merchant/1.117.2/1.117.3

The gemspecs still point towards the now-private GitHub repos, so the links on RubyGems (and in dependabot PRs here on GitHub, which is what prompted me to open this issue in the first place) are also 404s.

The gemspecs could have also included a `post_install_message` to make it abundantly clear what the latest release was for.
